import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { sendCommand, subscribe } from './api/websocket'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

type PaneArgs = {
  text: string,
  onClick?: () => any | undefined,
};

export const Pane = ({ text, onClick }: PaneArgs) => {
  return (
    <div style={{ flexGrow: 1, padding: '1rem' }}>
      <div 
        onClick={onClick}
        style={{ width: '100%', height: '100%', backgroundColor: 'white', color: 'black', display: 'flex',  alignItems: 'center', justifyContent: 'center' }}
      >
        <div>
          {text}
        </div>
      </div>
    </div>
  );
}

type SplitArgs = {
  direction: "column" | "column-reverse" | "row" | "row-reverse",
  children: any,
};

export const Split = ({ direction, children }: SplitArgs) => {
  return (
    <div style={{ flexGrow: 1, display: 'flex', flexDirection: direction }}>
      {children}
    </div>
  );
}

export default function Home() {
  const router = useRouter();
  const [state, setState]: [any, any] = useState(undefined);
  useEffect(() => {
    subscribe((x: any) => setState(x));
  });
  return (
    <>
      <Head>
        <title>هاب خانه هوشمند</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: 'flex', padding: '1rem', height: '100vh', width: '100vw' }}>
        {!state && <Pane text='ما متصل نیستیم. چند لحظه صبر کنید.' />}
        {state && <Split direction='row'>
          <Split direction='column'>
            {Object.keys(state.devices).map((x) => <Pane key={x} text={x} onClick={() => router.push(`/locations/${x}`)} />)}
          </Split>
          <Split direction='column'>
            <Pane text='قواعد' onClick={() => router.push(`/rules`)} />
            <Split direction='row'>
              <Pane text={`هاب متصل ${state.hub ? 'است' : 'نیست' }`} />
              <Pane text='تنظیمات' />
            </Split>
          </Split>
        </Split>}
      </div>
    </>
  )
}
